Fix compiler error with JIT when Zba is disabled
When using 'make ENABLE_Zba=0 ENABLE_JIT=1', the following errors are
observed:

src/jit.c:1760:17: error: ‘do_sh3add’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_sh2add’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_sh1add’ defined but not used [-Werror=unused-function]

Include 'Zba' in EXT_LIST to ensure instructions like 'sh3add',
'sh2add', and 'sh1add' are properly handled, resolving unused function
errors during JIT builds.