Fix compiler error with when Zicsr is disabled
When using 'make ENABLE_Zicsr=0', the following error is observed:

src/emulate.c:561:10: error: ‘rv_insn_csrrw’ undeclared (first use in this function); did you mean ‘rv_insn_csrai’?
  561 |     case rv_insn_csrrw:
      |          ^~~~~~~~~~~~~
      |          rv_insn_csrai

The error occurs because CSR instruction enums are only defined when
the Zicsr extension is enabled. By adding the feature guard, we ensure
the switch cases are only compiled when the required instruction
definitions are available.